name = "casto-workers"
main = "src/index.ts"
compatibility_date = "2024-09-22"
compatibility_flags = ["nodejs_compat"]

[env.development]
name = "casto-workers-dev"
vars = { ENVIRONMENT = "development" }
routes = [
  { pattern = "casto.sb2024.xyz/api/*", zone_name = "sb2024.xyz" }
]
[[env.development.r2_buckets]]
binding = "TALENT_PHOTOS"
bucket_name = "talent-photos"

[env.preview]
name = "casto-workers-preview"
vars = { ENVIRONMENT = "preview" }

[env.production]
name = "casto-workers"
vars = { ENVIRONMENT = "production" }
[[env.production.r2_buckets]]
binding = "TALENT_PHOTOS"
bucket_name = "talent-photos"

# Variables (non-secret)
[vars]
ENVIRONMENT = "development"

# Secrets (use `wrangler secret put` to set)
# SUPABASE_URL
# SUPABASE_SERVICE_ROLE_KEY
# JWT_SECRET
# DATABASE_URL
# LINE_CHANNEL_SECRET
# STRIPE_SECRET_KEY

# KV Namespaces (disabled for development)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your_kv_namespace_id"
# preview_id = "your_preview_kv_namespace_id"

# Queues (disabled for development)
# [[queues.producers]]
# queue = "notifications"
# binding = "NOTIFICATION_QUEUE"

# [[queues.consumers]]
# queue = "notifications"
# max_batch_size = 10
# max_batch_timeout = 30
