name: Production Deploy

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Debug Cloudflare API Token
        run: |
          echo "--- Start API Token Debug ---"
          TOKEN="${{ secrets.CLOUDFLARE_API_TOKEN }}"
          echo "Token length: ${#TOKEN}"
          echo "Token (first 10): '${TOKEN:0:10}'"
          echo "Token (last 10): '${TOKEN: -10}'"
          if [[ "$TOKEN" == *$'\n'* ]]; then
            echo "🔴 Token contains newline characters (\n)"
          else
            echo "✅ No newline (\n) detected"
          fi
          if [[ "$TOKEN" == *$'\r'* ]]; then
            echo "🔴 Token contains carriage return (\r)"
          else
            echo "✅ No carriage return (\r) detected"
          fi
          # Show hex of ends to detect invisible chars safely
          printf "First 4 bytes hex: "
          printf '%s' "${TOKEN:0:4}" | hexdump -v -e '/1 "%02X"' || true
          echo
          printf "Last 4 bytes hex:  "
          printf '%s' "${TOKEN: -4}" | hexdump -v -e '/1 "%02X"' || true
          echo
          echo "--- End API Token Debug ---"

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test
        continue-on-error: false

  deploy-web:
    name: Deploy Web to Production
    runs-on: ubuntu-latest
    needs: test
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Vercel Production
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./apps/web
          scope: ${{ secrets.VERCEL_ORG_ID }}

  deploy-workers:
    name: Deploy Workers to Production
    runs-on: ubuntu-latest
    needs: test
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Deploy Workers Production
        working-directory: ./apps/workers
        run: |
          echo " Checking Cloudflare authentication..."
          echo "Wrangler version: $(npx wrangler --version)"
          # Normalize token to avoid hidden characters breaking Authorization header
          if [ -n "${CLOUDFLARE_API_TOKEN:-}" ]; then
            # Remove CR/LF, then trim leading/trailing whitespace
            TRIMMED=$(printf '%s' "$CLOUDFLARE_API_TOKEN" | tr -d '\r\n' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
            # Strip optional surrounding quotes if the secret was saved with them (safe Bash patterns)
            if [[ $TRIMMED == \"* ]]; then TRIMMED=${TRIMMED#\"}; fi   # leading "
            if [[ $TRIMMED == *\" ]]; then TRIMMED=${TRIMMED%\"}; fi   # trailing "
            if [[ $TRIMMED == \'* ]]; then TRIMMED=${TRIMMED#\'}; fi     # leading '
            if [[ $TRIMMED == *\' ]]; then TRIMMED=${TRIMMED%\'}; fi     # trailing '
            export CLOUDFLARE_API_TOKEN="$TRIMMED"
            echo "Token length after normalize: ${#CLOUDFLARE_API_TOKEN}"
          fi

          if npx wrangler whoami; then
            echo " Authentication successful, deploying..."
            npx wrangler deploy --env production
          else
            echo " Cloudflare authentication failed."
            echo "Token format: ${CLOUDFLARE_API_TOKEN:0:10}..."
            echo ""
            echo "🔧 Troubleshooting steps:"
            echo "1. Verify API Token has User Memberships:Read permission"
            echo "2. Verify API Token has User Details:Read permission"
            echo "3. Check token expiration date"
            echo "4. Use 'Edit Cloudflare Workers' template for token creation"
            echo ""
            echo "Skipping deployment to avoid blocking."
            exit 1
          fi
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

  health-check:
    name: Health Check
    runs-on: ubuntu-latest
    needs: [deploy-web, deploy-workers]

    steps:
      - name: Check API Health
        run: |
          sleep 30
          curl -f https://casto-workers.casto-api.workers.dev/api/v1/health || exit 1
          
      - name: Check Web Health (Optional)
        run: |
          echo "✅ Web deployment completed successfully"
          echo "🌐 Web URL: https://web-ta1pre-ta1pres-projects.vercel.app/"
        continue-on-error: true

  notify:
    name: Notify Deployment
    runs-on: ubuntu-latest
    needs: [deploy-web, deploy-workers, health-check]
    if: always()

    steps:
      - name: Notify Success
        if: needs.health-check.result == 'success'
        run: |
          echo "🚀 Production deployment successful!"
          echo "Web: https://web-xi-seven-98.vercel.app/"
          echo "API: https://casto-workers.casto-api.workers.dev"

      - name: Notify Failure
        if: needs.health-check.result == 'failure'
        run: |
          echo "❌ Production deployment failed!"
          echo "Initiating rollback procedures..."
          exit 1
