name: Production Deploy

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci


      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test
        continue-on-error: false

  deploy-web:
    name: Deploy Web to Production
    runs-on: ubuntu-latest
    needs: test
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Vercel Production
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./apps/web
          scope: ${{ secrets.VERCEL_ORG_ID }}

  deploy-workers:
    name: Deploy Workers to Production
    runs-on: ubuntu-latest
    needs: test
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Deploy Workers Production
        working-directory: ./apps/workers
        run: |
          echo "Checking Cloudflare authentication and deploying Workers..."
          # Minimal normalization to avoid hidden characters breaking Authorization header (no logging)
          if [ -n "${CLOUDFLARE_API_TOKEN:-}" ]; then
            # Remove CR/LF, then trim leading/trailing whitespace
            TRIMMED=$(printf '%s' "$CLOUDFLARE_API_TOKEN" | tr -d '\r\n' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
            # Strip optional surrounding quotes if the secret was saved with them (safe Bash patterns)
            if [[ $TRIMMED == \"* ]]; then TRIMMED=${TRIMMED#\"}; fi   # leading "
            if [[ $TRIMMED == *\" ]]; then TRIMMED=${TRIMMED%\"}; fi   # trailing "
            if [[ $TRIMMED == \\'* ]]; then TRIMMED=${TRIMMED#\\'}; fi     # leading '
            if [[ $TRIMMED == *\\' ]]; then TRIMMED=${TRIMMED%\\'}; fi     # trailing '
            export CLOUDFLARE_API_TOKEN="$TRIMMED"
          fi

          if npx wrangler whoami; then
            echo "Authentication OK. Deploying..."
            npx wrangler deploy --env production
          else
            echo "Cloudflare authentication failed. Skipping deployment."
            exit 1
          fi
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

  health-check:
    name: Health Check
    runs-on: ubuntu-latest
    needs: [deploy-web, deploy-workers]

    steps:
      - name: Check API Health
        run: |
          sleep 30
          curl -f https://casto-workers.casto-api.workers.dev/api/v1/health || exit 1
          
      - name: Check Web Health (Optional)
        run: |
          echo "✅ Web deployment completed successfully"
          echo "🌐 Web URL: https://web-ta1pre-ta1pres-projects.vercel.app/"
        continue-on-error: true

  notify:
    name: Notify Deployment
    runs-on: ubuntu-latest
    needs: [deploy-web, deploy-workers, health-check]
    if: always()

    steps:
      - name: Notify Success
        if: needs.health-check.result == 'success'
        run: |
          echo "🚀 Production deployment successful!"
          echo "Web: https://casto.app"
          echo "API: https://casto-workers.casto-api.workers.dev"

      - name: Notify Failure
        if: needs.health-check.result == 'failure'
        run: |
          echo "❌ Production deployment failed!"
          echo "Initiating rollback procedures..."
          exit 1
